### ISSUE TITLE
infinite loop in .clean_geometry()

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#15]
**Describe the bug**
Hi Robbie

With close geometry coordinates being created followed by a clean_geometry, I've noted its possible for the code to get in what appears to be an infinite loop.

**To Reproduce**
Steps to reproduce the behavior with a small r_out applied and verbose=True with the CeeSection class. You can see it just keeps revisiting the same points during the clean geometry operation:-
```
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import CrossSection

# geometry of example channel
t = 1.16
d = 150
b = 40
l = 15
r_out = .1
n_r = 5

# create 2 channels, mirror second channel
channel1 = sections.CeeSection(d=d, b=b, l=l, t=t, r_out=(r_out), n_r=n_r)
channel2 = sections.CeeSection(d=d, b=b, l=l, t=t, r_out=(r_out), n_r=n_r)
channel2.mirror_section(axis='y', mirror_point=[0, 0])

# merge the two channels into a single section
geometry = sections.MergedSection([channel1, channel2])

# clean the geometry
geometry.clean_geometry(verbose=True)
```
![image](https://user-images.githubusercontent.com/36808164/61503564-45551e80-aa2c-11e9-867d-4d9266697b8b.png)

**Expected behavior**
Some way of detecting whatever scenario results in the looping, and either raising an exception or handling it in some way.

**Desktop (please complete the following information):**
 - Version 1.05 (latest)

**Comment by robbievanleeuwen** [comment]
Hi Agent,

Thanks for picking this up. After a bit of remembering how I implemented the overlapping check, turns out the tolerance I was using to see if lines were collinear was dependent on the length of the facets. I have modified the tolerance so that is dependent on the length of the facets - should make this algorithm more robust.

Let me know if you find any other issues with the geometry cleaning as I had a fair bit of difficulty with it and it's a bit of a monster.

Fix implemented in 9d74737.

Cheers,
Robbie
