### ISSUE TITLE
Cross sections with unconnected parts.

### ISSUE THREAD

**Issue by NicoEfst** [robbievanleeuwen/section-properties#26]
Hi,

my name is Nick and I am a Structural Engineer. I 've been recently using the section-properties package (great work by the way!) to calculate the properties of cross sections that are comprised from at least two unconnected parts (see the picture below), since I could not find any other commercial (e.g. NASTRAN, ABAQUS) that can calculate the properties of such cross sections.
![unconnected_parts](https://user-images.githubusercontent.com/25159051/89736653-9b4f9680-da73-11ea-83ca-b8ec1312044c.png)

I have two questions:
1) When calculating the warping function (w) following the Saint-Venant Torsion theorem, are these unconnected parts assumed to deform as a rigid body on the plane of the cross section? Or to rephrase, do we assume that these unconnected parts deform as a rigid body on the plane of the cross section? This is important for me so that I can interpret the resulting torsional constant, warping constant, etc.
2) Is the above-mentioned assumption of in-plane rigid body deformation also applicable to the calculation of the stress functions (PSI, PHI)? In this case I want to interpret the resulting shear deformation coefficients.

**Comment by Agent6-6-6** [comment]
It's not possible to analyse an unconnected series of sections like this. 

Read the notes on unconnected geometry here at the bottom of the merging geometry section of the docs:-

https://sectionproperties.readthedocs.io/en/latest/rst/geom_mesh.html?highlight=connect#merging-geometries

For two separate geometries, the torsion and warping constants will likely be the sum of the two separate geometry objects if they were actually connected. But since they are not connected (except maybe discretely at regular spacings) then you would need to treat them as two separate members in whatever analysis you are undertaking and model the interconnection.

**Comment by NicoEfst** [comment]
Thanks Agent6-6-6 for the quick response.
