### ISSUE TITLE
Units error in meshing module

### ISSUE THREAD

**Issue by thomas-ward27** [robbievanleeuwen/section-properties#413]
hi  Robbie
there is some bug in the meshing module when meshing in metres, I would expect both the following to give the same mesh

```python
d=50
t=5
sections.box_girder_section(d=d, b_t=d,b_b=d, t_ft=t,t_fb=t,t_w=t)#, r_out=15, n_r=16)
rhs_mesh = rhs_geometry.create_mesh(mesh_sizes=[t/2])
rhs_section.plot_mesh(pause=False)
    
d/=1e3
t/=1e3
rhs_mesh = rhs_geometry.create_mesh(mesh_sizes=[t/2])
rhs_section.plot_mesh(pause=False)
```

**Comment by robbievanleeuwen** [comment]
Hi @thomas-ward27, the `mesh_sizes` parameter describes the maximum mesh element area and not length, this is why you are not getting the same mesh. See the [docs](https://sectionproperties.readthedocs.io/en/stable/user_guide/meshing.html) for more info.

The code in your original post is missing several references so I based my answer off the following, including the fix for the mesh size (requires an additional scaling factor to ensure the mesh size is in square metres). I get the same mesh for both cases.

```python
import sectionproperties.pre.library.steel_sections as sections
from sectionproperties.analysis import Section

# millimetres
d=50
t=5
rhs_geometry = sections.box_girder_section(d=d, b_t=d,b_b=d, t_ft=t,t_fb=t,t_w=t)#, r_out=15, n_r=16)
rhs_mesh = rhs_geometry.create_mesh(mesh_sizes=[t/2])
rhs_section = Section(rhs_mesh)
rhs_section.plot_mesh()

# metres
d=50e-3
t=5e-3
rhs_geometry = sections.box_girder_section(d=d, b_t=d,b_b=d, t_ft=t,t_fb=t,t_w=t)#, r_out=15, n_r=16)
rhs_mesh = rhs_geometry.create_mesh(mesh_sizes=[(t/2)/1e3])
rhs_section = Section(rhs_mesh)
rhs_section.plot_mesh()
```

**Comment by thomas-ward27** [comment]
Thanks Robbie,
area makes sense
sorry I didn't read the documentation before bothering you with that spam.

regards

Thomas
