### ISSUE TITLE
Plastic moment for composite sections with "get_mp()" function

### ISSUE THREAD

**Issue by manjolosa** [robbievanleeuwen/section-properties#460]
- [x] I have searched the [issues](https://github.com/robbievanleeuwen/section-properties/issues)
      of this repo and believe that this is not a duplicate.

## Issue

Hi Robbie,

I really enjoy you sectionproperties and concreteproperties modules. Congrats on your work.

I am developing a scrip to check composite concrete and steel sections following eurocode 4. I am using book examples to verify my results and I can't match my book example plastic moments to the ones from the "get_mp()" function.

I tried calculating by hand the plastic moment for the steel-timber section example in the sectionproperties documentation. The hand calculation resulted in 441.79kNm and the sectionproperties results in the documention return "mp_xx" = 485.81kNm.

The plastic neutral axis position from my book examples allways match the sectionproperties' plastic neutral axis position, which is a good sign. 

I also tried the "get_mp()" function with a simple non composite steel section and the results match perfectly.

I don't know if I am missing something or if there is a bug on the "get_mp()" function.

Thanks for the help.

Best Regards,

**Comment by robbievanleeuwen** [comment]
Hi @manjolosa, if you post the example with working I'd be happy to have a look into it!

**Comment by manjolosa** [comment]
Hi Robbie,

Thank you for the quick reply.

Taking for example the composite section in the sectionproperties documentation. I attached a calculation of the plastic moment in excel and a comparission to the result in the sectionproperties documention.

The excel calculation results in 441.79kNm and the sectionproperties results in the documention return "mp_xx" = 485.81kNm.

I don't understand why there would be a difference between the two results.

[Composite_doc_example.xlsx](https://github.com/user-attachments/files/17181737/Composite_doc_example.xlsx)

**Comment by robbievanleeuwen** [comment]
Thanks @manjolosa for bringing this to my attention! It looks like there may be a bug affecting the calculation of plastic properties for composite sections only, which wasn't picked up in the current testing suite. I'll work to have a fix and release in the next few days 👍

**Comment by robbievanleeuwen** [comment]
Hi @manjolosa thanks again for highlighting this. The test suite now includes this example and another couple of composite plastic section examples. Note that the [example](https://sectionproperties.readthedocs.io/en/latest/examples/materials/composite_analysis.html#Display-Analysis-Results) reports `mp_xx = 450 kN.m`, which is slightly higher than your excel calculation due to the presence of root radii. The new example in the [tests](https://github.com/robbievanleeuwen/section-properties/blob/master/tests/analysis/test_plastic.py#L195) removes the root radius and gets the same result as your excel spreadsheet. A new release of `sectionproperties` is imminent.

**Comment by manjolosa** [comment]
Hi Robbie. Thanks for this. It´s a really life saver for me. You have developed a great tool for structural engineers. Looking forward for the new release.
